// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/prism.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrismService_Index_FullMethodName           = "/prism.PrismService/Index"
	PrismService_Search_FullMethodName          = "/prism.PrismService/Search"
	PrismService_OpenResult_FullMethodName      = "/prism.PrismService/OpenResult"
	PrismService_ConnectDatabase_FullMethodName = "/prism.PrismService/ConnectDatabase"
	PrismService_GetStats_FullMethodName        = "/prism.PrismService/GetStats"
	PrismService_GetSystemInfo_FullMethodName   = "/prism.PrismService/GetSystemInfo"
)

// PrismServiceClient is the client API for PrismService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrismServiceClient interface {
	Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgress], error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	OpenResult(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	ConnectDatabase(ctx context.Context, in *ConnectDatabaseRequest, opts ...grpc.CallOption) (*ConnectDatabaseResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error)
}

type prismServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrismServiceClient(cc grpc.ClientConnInterface) PrismServiceClient {
	return &prismServiceClient{cc}
}

func (c *prismServiceClient) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PrismService_ServiceDesc.Streams[0], PrismService_Index_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexRequest, IndexProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrismService_IndexClient = grpc.ServerStreamingClient[IndexProgress]

func (c *prismServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, PrismService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) OpenResult(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, PrismService_OpenResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) ConnectDatabase(ctx context.Context, in *ConnectDatabaseRequest, opts ...grpc.CallOption) (*ConnectDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectDatabaseResponse)
	err := c.cc.Invoke(ctx, PrismService_ConnectDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, PrismService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemInfoResponse)
	err := c.cc.Invoke(ctx, PrismService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrismServiceServer is the server API for PrismService service.
// All implementations must embed UnimplementedPrismServiceServer
// for forward compatibility.
type PrismServiceServer interface {
	Index(*IndexRequest, grpc.ServerStreamingServer[IndexProgress]) error
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	OpenResult(context.Context, *OpenRequest) (*OpenResponse, error)
	ConnectDatabase(context.Context, *ConnectDatabaseRequest) (*ConnectDatabaseResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error)
	mustEmbedUnimplementedPrismServiceServer()
}

// UnimplementedPrismServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrismServiceServer struct{}

func (UnimplementedPrismServiceServer) Index(*IndexRequest, grpc.ServerStreamingServer[IndexProgress]) error {
	return status.Error(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedPrismServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedPrismServiceServer) OpenResult(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenResult not implemented")
}
func (UnimplementedPrismServiceServer) ConnectDatabase(context.Context, *ConnectDatabaseRequest) (*ConnectDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectDatabase not implemented")
}
func (UnimplementedPrismServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedPrismServiceServer) GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedPrismServiceServer) mustEmbedUnimplementedPrismServiceServer() {}
func (UnimplementedPrismServiceServer) testEmbeddedByValue()                      {}

// UnsafePrismServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrismServiceServer will
// result in compilation errors.
type UnsafePrismServiceServer interface {
	mustEmbedUnimplementedPrismServiceServer()
}

func RegisterPrismServiceServer(s grpc.ServiceRegistrar, srv PrismServiceServer) {
	// If the following call panics, it indicates UnimplementedPrismServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrismService_ServiceDesc, srv)
}

func _PrismService_Index_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IndexRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrismServiceServer).Index(m, &grpc.GenericServerStream[IndexRequest, IndexProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrismService_IndexServer = grpc.ServerStreamingServer[IndexProgress]

func _PrismService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_OpenResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).OpenResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_OpenResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).OpenResult(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_ConnectDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).ConnectDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_ConnectDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).ConnectDatabase(ctx, req.(*ConnectDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrismService_ServiceDesc is the grpc.ServiceDesc for PrismService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrismService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prism.PrismService",
	HandlerType: (*PrismServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _PrismService_Search_Handler,
		},
		{
			MethodName: "OpenResult",
			Handler:    _PrismService_OpenResult_Handler,
		},
		{
			MethodName: "ConnectDatabase",
			Handler:    _PrismService_ConnectDatabase_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _PrismService_GetStats_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _PrismService_GetSystemInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Index",
			Handler:       _PrismService_Index_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/prism.proto",
}
