// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/prism.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_proto_prism_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{0}
}

type GetSystemInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Device         string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	SiglipModel    string                 `protobuf:"bytes,2,opt,name=siglip_model,json=siglipModel,proto3" json:"siglip_model,omitempty"`
	YoloModel      string                 `protobuf:"bytes,3,opt,name=yolo_model,json=yoloModel,proto3" json:"yolo_model,omitempty"`
	BackendVersion string                 `protobuf:"bytes,4,opt,name=backend_version,json=backendVersion,proto3" json:"backend_version,omitempty"`
	CpuCount       int32                  `protobuf:"varint,5,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryUsage    string                 `protobuf:"bytes,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_proto_prism_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemInfoResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *GetSystemInfoResponse) GetSiglipModel() string {
	if x != nil {
		return x.SiglipModel
	}
	return ""
}

func (x *GetSystemInfoResponse) GetYoloModel() string {
	if x != nil {
		return x.YoloModel
	}
	return ""
}

func (x *GetSystemInfoResponse) GetBackendVersion() string {
	if x != nil {
		return x.BackendVersion
	}
	return ""
}

func (x *GetSystemInfoResponse) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *GetSystemInfoResponse) GetMemoryUsage() string {
	if x != nil {
		return x.MemoryUsage
	}
	return ""
}

type ConnectDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbPath        string                 `protobuf:"bytes,1,opt,name=db_path,json=dbPath,proto3" json:"db_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDatabaseRequest) Reset() {
	*x = ConnectDatabaseRequest{}
	mi := &file_proto_prism_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDatabaseRequest) ProtoMessage() {}

func (x *ConnectDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDatabaseRequest.ProtoReflect.Descriptor instead.
func (*ConnectDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectDatabaseRequest) GetDbPath() string {
	if x != nil {
		return x.DbPath
	}
	return ""
}

type ConnectDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDatabaseResponse) Reset() {
	*x = ConnectDatabaseResponse{}
	mi := &file_proto_prism_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDatabaseResponse) ProtoMessage() {}

func (x *ConnectDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDatabaseResponse.ProtoReflect.Descriptor instead.
func (*ConnectDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectDatabaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_proto_prism_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{4}
}

func (x *IndexRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type IndexProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       int64                  `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	StatusMessage string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexProgress) Reset() {
	*x = IndexProgress{}
	mi := &file_proto_prism_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexProgress) ProtoMessage() {}

func (x *IndexProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexProgress.ProtoReflect.Descriptor instead.
func (*IndexProgress) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{5}
}

func (x *IndexProgress) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *IndexProgress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *IndexProgress) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryText     string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_prism_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

type SearchResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Path       string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Confidence float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasoning  string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	// New fields for UI details
	Resolution      string   `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	DateModified    string   `protobuf:"bytes,5,opt,name=date_modified,json=dateModified,proto3" json:"date_modified,omitempty"`
	FileSize        string   `protobuf:"bytes,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	DetectedObjects []string `protobuf:"bytes,7,rep,name=detected_objects,json=detectedObjects,proto3" json:"detected_objects,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_prism_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SearchResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SearchResult) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *SearchResult) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *SearchResult) GetDateModified() string {
	if x != nil {
		return x.DateModified
	}
	return ""
}

func (x *SearchResult) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *SearchResult) GetDetectedObjects() []string {
	if x != nil {
		return x.DetectedObjects
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_prism_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_prism_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{9}
}

func (x *OpenRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_prism_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{10}
}

func (x *OpenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_prism_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{11}
}

type DatasetMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalFrames     int64                  `protobuf:"varint,1,opt,name=total_frames,json=totalFrames,proto3" json:"total_frames,omitempty"`
	TotalEmbeddings int64                  `protobuf:"varint,2,opt,name=total_embeddings,json=totalEmbeddings,proto3" json:"total_embeddings,omitempty"`
	LastIndexed     string                 `protobuf:"bytes,3,opt,name=last_indexed,json=lastIndexed,proto3" json:"last_indexed,omitempty"`
	DbPath          string                 `protobuf:"bytes,4,opt,name=db_path,json=dbPath,proto3" json:"db_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DatasetMetadata) Reset() {
	*x = DatasetMetadata{}
	mi := &file_proto_prism_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetMetadata) ProtoMessage() {}

func (x *DatasetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetMetadata.ProtoReflect.Descriptor instead.
func (*DatasetMetadata) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{12}
}

func (x *DatasetMetadata) GetTotalFrames() int64 {
	if x != nil {
		return x.TotalFrames
	}
	return 0
}

func (x *DatasetMetadata) GetTotalEmbeddings() int64 {
	if x != nil {
		return x.TotalEmbeddings
	}
	return 0
}

func (x *DatasetMetadata) GetLastIndexed() string {
	if x != nil {
		return x.LastIndexed
	}
	return ""
}

func (x *DatasetMetadata) GetDbPath() string {
	if x != nil {
		return x.DbPath
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *DatasetMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_prism_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prism_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_prism_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsResponse) GetMetadata() *DatasetMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_prism_proto protoreflect.FileDescriptor

const file_proto_prism_proto_rawDesc = "" +
	"\n" +
	"\x11proto/prism.proto\x12\x05prism\"\x16\n" +
	"\x14GetSystemInfoRequest\"\xda\x01\n" +
	"\x15GetSystemInfoResponse\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12!\n" +
	"\fsiglip_model\x18\x02 \x01(\tR\vsiglipModel\x12\x1d\n" +
	"\n" +
	"yolo_model\x18\x03 \x01(\tR\tyoloModel\x12'\n" +
	"\x0fbackend_version\x18\x04 \x01(\tR\x0ebackendVersion\x12\x1b\n" +
	"\tcpu_count\x18\x05 \x01(\x05R\bcpuCount\x12!\n" +
	"\fmemory_usage\x18\x06 \x01(\tR\vmemoryUsage\"1\n" +
	"\x16ConnectDatabaseRequest\x12\x17\n" +
	"\adb_path\x18\x01 \x01(\tR\x06dbPath\"M\n" +
	"\x17ConnectDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\fIndexRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"f\n" +
	"\rIndexProgress\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x03R\acurrent\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\".\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\"\xed\x01\n" +
	"\fSearchResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\tR\n" +
	"resolution\x12#\n" +
	"\rdate_modified\x18\x05 \x01(\tR\fdateModified\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\tR\bfileSize\x12)\n" +
	"\x10detected_objects\x18\a \x03(\tR\x0fdetectedObjects\"?\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.prism.SearchResultR\aresults\"*\n" +
	"\vOpenRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"B\n" +
	"\fOpenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fGetStatsRequest\"\x9b\x01\n" +
	"\x0fDatasetMetadata\x12!\n" +
	"\ftotal_frames\x18\x01 \x01(\x03R\vtotalFrames\x12)\n" +
	"\x10total_embeddings\x18\x02 \x01(\x03R\x0ftotalEmbeddings\x12!\n" +
	"\flast_indexed\x18\x03 \x01(\tR\vlastIndexed\x12\x17\n" +
	"\adb_path\x18\x04 \x01(\tR\x06dbPath\"F\n" +
	"\x10GetStatsResponse\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.prism.DatasetMetadataR\bmetadata2\x99\x03\n" +
	"\fPrismService\x126\n" +
	"\x05Index\x12\x13.prism.IndexRequest\x1a\x14.prism.IndexProgress\"\x000\x01\x127\n" +
	"\x06Search\x12\x14.prism.SearchRequest\x1a\x15.prism.SearchResponse\"\x00\x127\n" +
	"\n" +
	"OpenResult\x12\x12.prism.OpenRequest\x1a\x13.prism.OpenResponse\"\x00\x12R\n" +
	"\x0fConnectDatabase\x12\x1d.prism.ConnectDatabaseRequest\x1a\x1e.prism.ConnectDatabaseResponse\"\x00\x12=\n" +
	"\bGetStats\x12\x16.prism.GetStatsRequest\x1a\x17.prism.GetStatsResponse\"\x00\x12L\n" +
	"\rGetSystemInfo\x12\x1b.prism.GetSystemInfoRequest\x1a\x1c.prism.GetSystemInfoResponse\"\x00B Z\x1egithub.com/sjanney/prism/protob\x06proto3"

var (
	file_proto_prism_proto_rawDescOnce sync.Once
	file_proto_prism_proto_rawDescData []byte
)

func file_proto_prism_proto_rawDescGZIP() []byte {
	file_proto_prism_proto_rawDescOnce.Do(func() {
		file_proto_prism_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_prism_proto_rawDesc), len(file_proto_prism_proto_rawDesc)))
	})
	return file_proto_prism_proto_rawDescData
}

var file_proto_prism_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_prism_proto_goTypes = []any{
	(*GetSystemInfoRequest)(nil),    // 0: prism.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),   // 1: prism.GetSystemInfoResponse
	(*ConnectDatabaseRequest)(nil),  // 2: prism.ConnectDatabaseRequest
	(*ConnectDatabaseResponse)(nil), // 3: prism.ConnectDatabaseResponse
	(*IndexRequest)(nil),            // 4: prism.IndexRequest
	(*IndexProgress)(nil),           // 5: prism.IndexProgress
	(*SearchRequest)(nil),           // 6: prism.SearchRequest
	(*SearchResult)(nil),            // 7: prism.SearchResult
	(*SearchResponse)(nil),          // 8: prism.SearchResponse
	(*OpenRequest)(nil),             // 9: prism.OpenRequest
	(*OpenResponse)(nil),            // 10: prism.OpenResponse
	(*GetStatsRequest)(nil),         // 11: prism.GetStatsRequest
	(*DatasetMetadata)(nil),         // 12: prism.DatasetMetadata
	(*GetStatsResponse)(nil),        // 13: prism.GetStatsResponse
}
var file_proto_prism_proto_depIdxs = []int32{
	7,  // 0: prism.SearchResponse.results:type_name -> prism.SearchResult
	12, // 1: prism.GetStatsResponse.metadata:type_name -> prism.DatasetMetadata
	4,  // 2: prism.PrismService.Index:input_type -> prism.IndexRequest
	6,  // 3: prism.PrismService.Search:input_type -> prism.SearchRequest
	9,  // 4: prism.PrismService.OpenResult:input_type -> prism.OpenRequest
	2,  // 5: prism.PrismService.ConnectDatabase:input_type -> prism.ConnectDatabaseRequest
	11, // 6: prism.PrismService.GetStats:input_type -> prism.GetStatsRequest
	0,  // 7: prism.PrismService.GetSystemInfo:input_type -> prism.GetSystemInfoRequest
	5,  // 8: prism.PrismService.Index:output_type -> prism.IndexProgress
	8,  // 9: prism.PrismService.Search:output_type -> prism.SearchResponse
	10, // 10: prism.PrismService.OpenResult:output_type -> prism.OpenResponse
	3,  // 11: prism.PrismService.ConnectDatabase:output_type -> prism.ConnectDatabaseResponse
	13, // 12: prism.PrismService.GetStats:output_type -> prism.GetStatsResponse
	1,  // 13: prism.PrismService.GetSystemInfo:output_type -> prism.GetSystemInfoResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_prism_proto_init() }
func file_proto_prism_proto_init() {
	if File_proto_prism_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_prism_proto_rawDesc), len(file_proto_prism_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_prism_proto_goTypes,
		DependencyIndexes: file_proto_prism_proto_depIdxs,
		MessageInfos:      file_proto_prism_proto_msgTypes,
	}.Build()
	File_proto_prism_proto = out.File
	file_proto_prism_proto_goTypes = nil
	file_proto_prism_proto_depIdxs = nil
}
