# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prism_pb2 as prism__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in prism_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrismServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Index = channel.unary_stream(
                '/prism.PrismService/Index',
                request_serializer=prism__pb2.IndexRequest.SerializeToString,
                response_deserializer=prism__pb2.IndexProgress.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/prism.PrismService/Search',
                request_serializer=prism__pb2.SearchRequest.SerializeToString,
                response_deserializer=prism__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.OpenResult = channel.unary_unary(
                '/prism.PrismService/OpenResult',
                request_serializer=prism__pb2.OpenRequest.SerializeToString,
                response_deserializer=prism__pb2.OpenResponse.FromString,
                _registered_method=True)
        self.ConnectDatabase = channel.unary_unary(
                '/prism.PrismService/ConnectDatabase',
                request_serializer=prism__pb2.ConnectDatabaseRequest.SerializeToString,
                response_deserializer=prism__pb2.ConnectDatabaseResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/prism.PrismService/GetStats',
                request_serializer=prism__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=prism__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.GetSystemInfo = channel.unary_unary(
                '/prism.PrismService/GetSystemInfo',
                request_serializer=prism__pb2.GetSystemInfoRequest.SerializeToString,
                response_deserializer=prism__pb2.GetSystemInfoResponse.FromString,
                _registered_method=True)


class PrismServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrismServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Index': grpc.unary_stream_rpc_method_handler(
                    servicer.Index,
                    request_deserializer=prism__pb2.IndexRequest.FromString,
                    response_serializer=prism__pb2.IndexProgress.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=prism__pb2.SearchRequest.FromString,
                    response_serializer=prism__pb2.SearchResponse.SerializeToString,
            ),
            'OpenResult': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenResult,
                    request_deserializer=prism__pb2.OpenRequest.FromString,
                    response_serializer=prism__pb2.OpenResponse.SerializeToString,
            ),
            'ConnectDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectDatabase,
                    request_deserializer=prism__pb2.ConnectDatabaseRequest.FromString,
                    response_serializer=prism__pb2.ConnectDatabaseResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=prism__pb2.GetStatsRequest.FromString,
                    response_serializer=prism__pb2.GetStatsResponse.SerializeToString,
            ),
            'GetSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInfo,
                    request_deserializer=prism__pb2.GetSystemInfoRequest.FromString,
                    response_serializer=prism__pb2.GetSystemInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prism.PrismService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prism.PrismService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrismService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/prism.PrismService/Index',
            prism__pb2.IndexRequest.SerializeToString,
            prism__pb2.IndexProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prism.PrismService/Search',
            prism__pb2.SearchRequest.SerializeToString,
            prism__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prism.PrismService/OpenResult',
            prism__pb2.OpenRequest.SerializeToString,
            prism__pb2.OpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prism.PrismService/ConnectDatabase',
            prism__pb2.ConnectDatabaseRequest.SerializeToString,
            prism__pb2.ConnectDatabaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prism.PrismService/GetStats',
            prism__pb2.GetStatsRequest.SerializeToString,
            prism__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prism.PrismService/GetSystemInfo',
            prism__pb2.GetSystemInfoRequest.SerializeToString,
            prism__pb2.GetSystemInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
